version: "3.3"

services:
    mongo:
        image: mongo:latest
        ports:
            - ${MONGO_PORT}:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
        networks:
            - gg-bflow-network
    memcache:
        image: memcached:alpine
        ports:
            - ${MEMCACHE_PORT}:11211
        command: -I 10m -m 200m
        networks:
            - gg-bflow-network
networks:
    gg-bflow-network:
        external: true
