// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: gg-bflow.proto

package gg_bflow

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ok struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	Meta    string `protobuf:"bytes,2,opt,name=Meta,proto3" json:"Meta,omitempty"`
}

func (x *Ok) Reset() {
	*x = Ok{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gg_bflow_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ok) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ok) ProtoMessage() {}

func (x *Ok) ProtoReflect() protoreflect.Message {
	mi := &file_gg_bflow_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ok.ProtoReflect.Descriptor instead.
func (*Ok) Descriptor() ([]byte, []int) {
	return file_gg_bflow_proto_rawDescGZIP(), []int{0}
}

func (x *Ok) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Ok) GetMeta() string {
	if x != nil {
		return x.Meta
	}
	return ""
}

type HealthCheckRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uptime string `protobuf:"bytes,1,opt,name=Uptime,proto3" json:"Uptime,omitempty"`
	Meta   string `protobuf:"bytes,2,opt,name=Meta,proto3" json:"Meta,omitempty"`
}

func (x *HealthCheckRes) Reset() {
	*x = HealthCheckRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gg_bflow_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HealthCheckRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRes) ProtoMessage() {}

func (x *HealthCheckRes) ProtoReflect() protoreflect.Message {
	mi := &file_gg_bflow_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRes.ProtoReflect.Descriptor instead.
func (*HealthCheckRes) Descriptor() ([]byte, []int) {
	return file_gg_bflow_proto_rawDescGZIP(), []int{1}
}

func (x *HealthCheckRes) GetUptime() string {
	if x != nil {
		return x.Uptime
	}
	return ""
}

func (x *HealthCheckRes) GetMeta() string {
	if x != nil {
		return x.Meta
	}
	return ""
}

type LoadDiscreteFlowArg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
}

func (x *LoadDiscreteFlowArg) Reset() {
	*x = LoadDiscreteFlowArg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gg_bflow_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadDiscreteFlowArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadDiscreteFlowArg) ProtoMessage() {}

func (x *LoadDiscreteFlowArg) ProtoReflect() protoreflect.Message {
	mi := &file_gg_bflow_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadDiscreteFlowArg.ProtoReflect.Descriptor instead.
func (*LoadDiscreteFlowArg) Descriptor() ([]byte, []int) {
	return file_gg_bflow_proto_rawDescGZIP(), []int{2}
}

func (x *LoadDiscreteFlowArg) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type LoadFlowArg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key  string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Rate int64  `protobuf:"varint,2,opt,name=Rate,proto3" json:"Rate,omitempty"`
}

func (x *LoadFlowArg) Reset() {
	*x = LoadFlowArg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gg_bflow_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadFlowArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadFlowArg) ProtoMessage() {}

func (x *LoadFlowArg) ProtoReflect() protoreflect.Message {
	mi := &file_gg_bflow_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadFlowArg.ProtoReflect.Descriptor instead.
func (*LoadFlowArg) Descriptor() ([]byte, []int) {
	return file_gg_bflow_proto_rawDescGZIP(), []int{3}
}

func (x *LoadFlowArg) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *LoadFlowArg) GetRate() int64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

type LoadMetaArg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
}

func (x *LoadMetaArg) Reset() {
	*x = LoadMetaArg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gg_bflow_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadMetaArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadMetaArg) ProtoMessage() {}

func (x *LoadMetaArg) ProtoReflect() protoreflect.Message {
	mi := &file_gg_bflow_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadMetaArg.ProtoReflect.Descriptor instead.
func (*LoadMetaArg) Descriptor() ([]byte, []int) {
	return file_gg_bflow_proto_rawDescGZIP(), []int{4}
}

func (x *LoadMetaArg) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type SendFlowArg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key  string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Byte []byte `protobuf:"bytes,2,opt,name=Byte,proto3" json:"Byte,omitempty"`
}

func (x *SendFlowArg) Reset() {
	*x = SendFlowArg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gg_bflow_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendFlowArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFlowArg) ProtoMessage() {}

func (x *SendFlowArg) ProtoReflect() protoreflect.Message {
	mi := &file_gg_bflow_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFlowArg.ProtoReflect.Descriptor instead.
func (*SendFlowArg) Descriptor() ([]byte, []int) {
	return file_gg_bflow_proto_rawDescGZIP(), []int{5}
}

func (x *SendFlowArg) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SendFlowArg) GetByte() []byte {
	if x != nil {
		return x.Byte
	}
	return nil
}

type DiscreteFlowRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Byte []byte `protobuf:"bytes,1,opt,name=Byte,proto3" json:"Byte,omitempty"`
}

func (x *DiscreteFlowRes) Reset() {
	*x = DiscreteFlowRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gg_bflow_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiscreteFlowRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscreteFlowRes) ProtoMessage() {}

func (x *DiscreteFlowRes) ProtoReflect() protoreflect.Message {
	mi := &file_gg_bflow_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscreteFlowRes.ProtoReflect.Descriptor instead.
func (*DiscreteFlowRes) Descriptor() ([]byte, []int) {
	return file_gg_bflow_proto_rawDescGZIP(), []int{6}
}

func (x *DiscreteFlowRes) GetByte() []byte {
	if x != nil {
		return x.Byte
	}
	return nil
}

type FlowRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Byte []byte `protobuf:"bytes,1,opt,name=Byte,proto3" json:"Byte,omitempty"`
	Info string `protobuf:"bytes,2,opt,name=Info,proto3" json:"Info,omitempty"`
}

func (x *FlowRes) Reset() {
	*x = FlowRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gg_bflow_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlowRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowRes) ProtoMessage() {}

func (x *FlowRes) ProtoReflect() protoreflect.Message {
	mi := &file_gg_bflow_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowRes.ProtoReflect.Descriptor instead.
func (*FlowRes) Descriptor() ([]byte, []int) {
	return file_gg_bflow_proto_rawDescGZIP(), []int{7}
}

func (x *FlowRes) GetByte() []byte {
	if x != nil {
		return x.Byte
	}
	return nil
}

func (x *FlowRes) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

type SendMetaArg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key  string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Meta string `protobuf:"bytes,2,opt,name=Meta,proto3" json:"Meta,omitempty"`
}

func (x *SendMetaArg) Reset() {
	*x = SendMetaArg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gg_bflow_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendMetaArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMetaArg) ProtoMessage() {}

func (x *SendMetaArg) ProtoReflect() protoreflect.Message {
	mi := &file_gg_bflow_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMetaArg.ProtoReflect.Descriptor instead.
func (*SendMetaArg) Descriptor() ([]byte, []int) {
	return file_gg_bflow_proto_rawDescGZIP(), []int{8}
}

func (x *SendMetaArg) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SendMetaArg) GetMeta() string {
	if x != nil {
		return x.Meta
	}
	return ""
}

type MetaRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key       string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Meta      string `protobuf:"bytes,2,opt,name=Meta,proto3" json:"Meta,omitempty"`
	CreatedAt int64  `protobuf:"varint,3,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt int64  `protobuf:"varint,4,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
}

func (x *MetaRes) Reset() {
	*x = MetaRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gg_bflow_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetaRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaRes) ProtoMessage() {}

func (x *MetaRes) ProtoReflect() protoreflect.Message {
	mi := &file_gg_bflow_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaRes.ProtoReflect.Descriptor instead.
func (*MetaRes) Descriptor() ([]byte, []int) {
	return file_gg_bflow_proto_rawDescGZIP(), []int{9}
}

func (x *MetaRes) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *MetaRes) GetMeta() string {
	if x != nil {
		return x.Meta
	}
	return ""
}

func (x *MetaRes) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *MetaRes) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

var File_gg_bflow_proto protoreflect.FileDescriptor

var file_gg_bflow_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x67, 0x67, 0x2d, 0x62, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x07, 0x67, 0x67, 0x62, 0x66, 0x6c, 0x6f, 0x77, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x32, 0x0a, 0x02, 0x4f, 0x6b, 0x12, 0x18, 0x0a, 0x07,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4d, 0x65, 0x74, 0x61, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4d, 0x65, 0x74, 0x61, 0x22, 0x3c, 0x0a, 0x0e, 0x48, 0x65,
	0x61, 0x6c, 0x74, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x55, 0x70, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x70,
	0x74, 0x69, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4d, 0x65, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x4d, 0x65, 0x74, 0x61, 0x22, 0x27, 0x0a, 0x13, 0x4c, 0x6f, 0x61, 0x64,
	0x44, 0x69, 0x73, 0x63, 0x72, 0x65, 0x74, 0x65, 0x46, 0x6c, 0x6f, 0x77, 0x41, 0x72, 0x67, 0x12,
	0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65,
	0x79, 0x22, 0x33, 0x0a, 0x0b, 0x4c, 0x6f, 0x61, 0x64, 0x46, 0x6c, 0x6f, 0x77, 0x41, 0x72, 0x67,
	0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b,
	0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x52, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x52, 0x61, 0x74, 0x65, 0x22, 0x1f, 0x0a, 0x0b, 0x4c, 0x6f, 0x61, 0x64, 0x4d, 0x65,
	0x74, 0x61, 0x41, 0x72, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x22, 0x33, 0x0a, 0x0b, 0x53, 0x65, 0x6e, 0x64, 0x46,
	0x6c, 0x6f, 0x77, 0x41, 0x72, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x42, 0x79, 0x74, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x42, 0x79, 0x74, 0x65, 0x22, 0x25, 0x0a, 0x0f,
	0x44, 0x69, 0x73, 0x63, 0x72, 0x65, 0x74, 0x65, 0x46, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x42, 0x79, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x42,
	0x79, 0x74, 0x65, 0x22, 0x31, 0x0a, 0x07, 0x46, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x42, 0x79, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x42, 0x79,
	0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x33, 0x0a, 0x0b, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65,
	0x74, 0x61, 0x41, 0x72, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x4d, 0x65, 0x74, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4d, 0x65, 0x74, 0x61, 0x22, 0x6b, 0x0a, 0x07, 0x4d,
	0x65, 0x74, 0x61, 0x52, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x4d, 0x65, 0x74, 0x61,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x1c, 0x0a, 0x09,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x32, 0x49, 0x0a, 0x07, 0x47, 0x47, 0x42, 0x46,
	0x6c, 0x6f, 0x77, 0x12, 0x3e, 0x0a, 0x0b, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x17, 0x2e, 0x67, 0x67, 0x62,
	0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x52, 0x65, 0x73, 0x32, 0xa1, 0x01, 0x0a, 0x0d, 0x47, 0x47, 0x42, 0x46, 0x6c, 0x6f, 0x77, 0x53,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x30, 0x0a, 0x0b, 0x53, 0x65, 0x6e, 0x64, 0x4f, 0x6e, 0x65,
	0x46, 0x6c, 0x6f, 0x77, 0x12, 0x14, 0x2e, 0x67, 0x67, 0x62, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x53,
	0x65, 0x6e, 0x64, 0x46, 0x6c, 0x6f, 0x77, 0x41, 0x72, 0x67, 0x1a, 0x0b, 0x2e, 0x67, 0x67, 0x62,
	0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x4f, 0x6b, 0x12, 0x2f, 0x0a, 0x08, 0x53, 0x65, 0x6e, 0x64, 0x46,
	0x6c, 0x6f, 0x77, 0x12, 0x14, 0x2e, 0x67, 0x67, 0x62, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x53, 0x65,
	0x6e, 0x64, 0x46, 0x6c, 0x6f, 0x77, 0x41, 0x72, 0x67, 0x1a, 0x0b, 0x2e, 0x67, 0x67, 0x62, 0x66,
	0x6c, 0x6f, 0x77, 0x2e, 0x4f, 0x6b, 0x28, 0x01, 0x12, 0x2d, 0x0a, 0x08, 0x53, 0x65, 0x6e, 0x64,
	0x4d, 0x65, 0x74, 0x61, 0x12, 0x14, 0x2e, 0x67, 0x67, 0x62, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x53,
	0x65, 0x6e, 0x64, 0x4d, 0x65, 0x74, 0x61, 0x41, 0x72, 0x67, 0x1a, 0x0b, 0x2e, 0x67, 0x67, 0x62,
	0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x4f, 0x6b, 0x32, 0xc5, 0x01, 0x0a, 0x0d, 0x47, 0x47, 0x42, 0x46,
	0x6c, 0x6f, 0x77, 0x4c, 0x6f, 0x61, 0x64, 0x65, 0x72, 0x12, 0x4a, 0x0a, 0x10, 0x4c, 0x6f, 0x61,
	0x64, 0x44, 0x69, 0x73, 0x63, 0x72, 0x65, 0x74, 0x65, 0x46, 0x6c, 0x6f, 0x77, 0x12, 0x1c, 0x2e,
	0x67, 0x67, 0x62, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x4c, 0x6f, 0x61, 0x64, 0x44, 0x69, 0x73, 0x63,
	0x72, 0x65, 0x74, 0x65, 0x46, 0x6c, 0x6f, 0x77, 0x41, 0x72, 0x67, 0x1a, 0x18, 0x2e, 0x67, 0x67,
	0x62, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x44, 0x69, 0x73, 0x63, 0x72, 0x65, 0x74, 0x65, 0x46, 0x6c,
	0x6f, 0x77, 0x52, 0x65, 0x73, 0x12, 0x34, 0x0a, 0x08, 0x4c, 0x6f, 0x61, 0x64, 0x46, 0x6c, 0x6f,
	0x77, 0x12, 0x14, 0x2e, 0x67, 0x67, 0x62, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x4c, 0x6f, 0x61, 0x64,
	0x46, 0x6c, 0x6f, 0x77, 0x41, 0x72, 0x67, 0x1a, 0x10, 0x2e, 0x67, 0x67, 0x62, 0x66, 0x6c, 0x6f,
	0x77, 0x2e, 0x46, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x73, 0x30, 0x01, 0x12, 0x32, 0x0a, 0x08, 0x4c,
	0x6f, 0x61, 0x64, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x14, 0x2e, 0x67, 0x67, 0x62, 0x66, 0x6c, 0x6f,
	0x77, 0x2e, 0x4c, 0x6f, 0x61, 0x64, 0x4d, 0x65, 0x74, 0x61, 0x41, 0x72, 0x67, 0x1a, 0x10, 0x2e,
	0x67, 0x67, 0x62, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x73, 0x42,
	0x17, 0x5a, 0x15, 0x61, 0x70, 0x70, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x3b,
	0x67, 0x67, 0x5f, 0x62, 0x66, 0x6c, 0x6f, 0x77, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gg_bflow_proto_rawDescOnce sync.Once
	file_gg_bflow_proto_rawDescData = file_gg_bflow_proto_rawDesc
)

func file_gg_bflow_proto_rawDescGZIP() []byte {
	file_gg_bflow_proto_rawDescOnce.Do(func() {
		file_gg_bflow_proto_rawDescData = protoimpl.X.CompressGZIP(file_gg_bflow_proto_rawDescData)
	})
	return file_gg_bflow_proto_rawDescData
}

var file_gg_bflow_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_gg_bflow_proto_goTypes = []interface{}{
	(*Ok)(nil),                  // 0: ggbflow.Ok
	(*HealthCheckRes)(nil),      // 1: ggbflow.HealthCheckRes
	(*LoadDiscreteFlowArg)(nil), // 2: ggbflow.LoadDiscreteFlowArg
	(*LoadFlowArg)(nil),         // 3: ggbflow.LoadFlowArg
	(*LoadMetaArg)(nil),         // 4: ggbflow.LoadMetaArg
	(*SendFlowArg)(nil),         // 5: ggbflow.SendFlowArg
	(*DiscreteFlowRes)(nil),     // 6: ggbflow.DiscreteFlowRes
	(*FlowRes)(nil),             // 7: ggbflow.FlowRes
	(*SendMetaArg)(nil),         // 8: ggbflow.SendMetaArg
	(*MetaRes)(nil),             // 9: ggbflow.MetaRes
	(*emptypb.Empty)(nil),       // 10: google.protobuf.Empty
}
var file_gg_bflow_proto_depIdxs = []int32{
	10, // 0: ggbflow.GGBFlow.HealthCheck:input_type -> google.protobuf.Empty
	5,  // 1: ggbflow.GGBFlowSender.SendOneFlow:input_type -> ggbflow.SendFlowArg
	5,  // 2: ggbflow.GGBFlowSender.SendFlow:input_type -> ggbflow.SendFlowArg
	8,  // 3: ggbflow.GGBFlowSender.SendMeta:input_type -> ggbflow.SendMetaArg
	2,  // 4: ggbflow.GGBFlowLoader.LoadDiscreteFlow:input_type -> ggbflow.LoadDiscreteFlowArg
	3,  // 5: ggbflow.GGBFlowLoader.LoadFlow:input_type -> ggbflow.LoadFlowArg
	4,  // 6: ggbflow.GGBFlowLoader.LoadMeta:input_type -> ggbflow.LoadMetaArg
	1,  // 7: ggbflow.GGBFlow.HealthCheck:output_type -> ggbflow.HealthCheckRes
	0,  // 8: ggbflow.GGBFlowSender.SendOneFlow:output_type -> ggbflow.Ok
	0,  // 9: ggbflow.GGBFlowSender.SendFlow:output_type -> ggbflow.Ok
	0,  // 10: ggbflow.GGBFlowSender.SendMeta:output_type -> ggbflow.Ok
	6,  // 11: ggbflow.GGBFlowLoader.LoadDiscreteFlow:output_type -> ggbflow.DiscreteFlowRes
	7,  // 12: ggbflow.GGBFlowLoader.LoadFlow:output_type -> ggbflow.FlowRes
	9,  // 13: ggbflow.GGBFlowLoader.LoadMeta:output_type -> ggbflow.MetaRes
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_gg_bflow_proto_init() }
func file_gg_bflow_proto_init() {
	if File_gg_bflow_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gg_bflow_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ok); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gg_bflow_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HealthCheckRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gg_bflow_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadDiscreteFlowArg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gg_bflow_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadFlowArg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gg_bflow_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadMetaArg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gg_bflow_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendFlowArg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gg_bflow_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiscreteFlowRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gg_bflow_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FlowRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gg_bflow_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendMetaArg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gg_bflow_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetaRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gg_bflow_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_gg_bflow_proto_goTypes,
		DependencyIndexes: file_gg_bflow_proto_depIdxs,
		MessageInfos:      file_gg_bflow_proto_msgTypes,
	}.Build()
	File_gg_bflow_proto = out.File
	file_gg_bflow_proto_rawDesc = nil
	file_gg_bflow_proto_goTypes = nil
	file_gg_bflow_proto_depIdxs = nil
}
