// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: gg-bflow.proto

package gg_bflow

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GGBFlowClient is the client API for GGBFlow service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GGBFlowClient interface {
	HealthCheck(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthCheckRes, error)
}

type gGBFlowClient struct {
	cc grpc.ClientConnInterface
}

func NewGGBFlowClient(cc grpc.ClientConnInterface) GGBFlowClient {
	return &gGBFlowClient{cc}
}

func (c *gGBFlowClient) HealthCheck(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthCheckRes, error) {
	out := new(HealthCheckRes)
	err := c.cc.Invoke(ctx, "/ggbflow.GGBFlow/HealthCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GGBFlowServer is the server API for GGBFlow service.
// All implementations must embed UnimplementedGGBFlowServer
// for forward compatibility
type GGBFlowServer interface {
	HealthCheck(context.Context, *emptypb.Empty) (*HealthCheckRes, error)
	mustEmbedUnimplementedGGBFlowServer()
}

// UnimplementedGGBFlowServer must be embedded to have forward compatible implementations.
type UnimplementedGGBFlowServer struct {
}

func (UnimplementedGGBFlowServer) HealthCheck(context.Context, *emptypb.Empty) (*HealthCheckRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedGGBFlowServer) mustEmbedUnimplementedGGBFlowServer() {}

// UnsafeGGBFlowServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GGBFlowServer will
// result in compilation errors.
type UnsafeGGBFlowServer interface {
	mustEmbedUnimplementedGGBFlowServer()
}

func RegisterGGBFlowServer(s grpc.ServiceRegistrar, srv GGBFlowServer) {
	s.RegisterService(&GGBFlow_ServiceDesc, srv)
}

func _GGBFlow_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GGBFlowServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ggbflow.GGBFlow/HealthCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GGBFlowServer).HealthCheck(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// GGBFlow_ServiceDesc is the grpc.ServiceDesc for GGBFlow service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GGBFlow_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ggbflow.GGBFlow",
	HandlerType: (*GGBFlowServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _GGBFlow_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gg-bflow.proto",
}

// GGBFlowSenderClient is the client API for GGBFlowSender service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GGBFlowSenderClient interface {
	SendOneFlow(ctx context.Context, in *SendFlowArg, opts ...grpc.CallOption) (*Ok, error)
	SendFlow(ctx context.Context, opts ...grpc.CallOption) (GGBFlowSender_SendFlowClient, error)
	SendMeta(ctx context.Context, in *SendMetaArg, opts ...grpc.CallOption) (*Ok, error)
}

type gGBFlowSenderClient struct {
	cc grpc.ClientConnInterface
}

func NewGGBFlowSenderClient(cc grpc.ClientConnInterface) GGBFlowSenderClient {
	return &gGBFlowSenderClient{cc}
}

func (c *gGBFlowSenderClient) SendOneFlow(ctx context.Context, in *SendFlowArg, opts ...grpc.CallOption) (*Ok, error) {
	out := new(Ok)
	err := c.cc.Invoke(ctx, "/ggbflow.GGBFlowSender/SendOneFlow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gGBFlowSenderClient) SendFlow(ctx context.Context, opts ...grpc.CallOption) (GGBFlowSender_SendFlowClient, error) {
	stream, err := c.cc.NewStream(ctx, &GGBFlowSender_ServiceDesc.Streams[0], "/ggbflow.GGBFlowSender/SendFlow", opts...)
	if err != nil {
		return nil, err
	}
	x := &gGBFlowSenderSendFlowClient{stream}
	return x, nil
}

type GGBFlowSender_SendFlowClient interface {
	Send(*SendFlowArg) error
	CloseAndRecv() (*Ok, error)
	grpc.ClientStream
}

type gGBFlowSenderSendFlowClient struct {
	grpc.ClientStream
}

func (x *gGBFlowSenderSendFlowClient) Send(m *SendFlowArg) error {
	return x.ClientStream.SendMsg(m)
}

func (x *gGBFlowSenderSendFlowClient) CloseAndRecv() (*Ok, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Ok)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gGBFlowSenderClient) SendMeta(ctx context.Context, in *SendMetaArg, opts ...grpc.CallOption) (*Ok, error) {
	out := new(Ok)
	err := c.cc.Invoke(ctx, "/ggbflow.GGBFlowSender/SendMeta", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GGBFlowSenderServer is the server API for GGBFlowSender service.
// All implementations must embed UnimplementedGGBFlowSenderServer
// for forward compatibility
type GGBFlowSenderServer interface {
	SendOneFlow(context.Context, *SendFlowArg) (*Ok, error)
	SendFlow(GGBFlowSender_SendFlowServer) error
	SendMeta(context.Context, *SendMetaArg) (*Ok, error)
	mustEmbedUnimplementedGGBFlowSenderServer()
}

// UnimplementedGGBFlowSenderServer must be embedded to have forward compatible implementations.
type UnimplementedGGBFlowSenderServer struct {
}

func (UnimplementedGGBFlowSenderServer) SendOneFlow(context.Context, *SendFlowArg) (*Ok, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendOneFlow not implemented")
}
func (UnimplementedGGBFlowSenderServer) SendFlow(GGBFlowSender_SendFlowServer) error {
	return status.Errorf(codes.Unimplemented, "method SendFlow not implemented")
}
func (UnimplementedGGBFlowSenderServer) SendMeta(context.Context, *SendMetaArg) (*Ok, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMeta not implemented")
}
func (UnimplementedGGBFlowSenderServer) mustEmbedUnimplementedGGBFlowSenderServer() {}

// UnsafeGGBFlowSenderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GGBFlowSenderServer will
// result in compilation errors.
type UnsafeGGBFlowSenderServer interface {
	mustEmbedUnimplementedGGBFlowSenderServer()
}

func RegisterGGBFlowSenderServer(s grpc.ServiceRegistrar, srv GGBFlowSenderServer) {
	s.RegisterService(&GGBFlowSender_ServiceDesc, srv)
}

func _GGBFlowSender_SendOneFlow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendFlowArg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GGBFlowSenderServer).SendOneFlow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ggbflow.GGBFlowSender/SendOneFlow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GGBFlowSenderServer).SendOneFlow(ctx, req.(*SendFlowArg))
	}
	return interceptor(ctx, in, info, handler)
}

func _GGBFlowSender_SendFlow_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GGBFlowSenderServer).SendFlow(&gGBFlowSenderSendFlowServer{stream})
}

type GGBFlowSender_SendFlowServer interface {
	SendAndClose(*Ok) error
	Recv() (*SendFlowArg, error)
	grpc.ServerStream
}

type gGBFlowSenderSendFlowServer struct {
	grpc.ServerStream
}

func (x *gGBFlowSenderSendFlowServer) SendAndClose(m *Ok) error {
	return x.ServerStream.SendMsg(m)
}

func (x *gGBFlowSenderSendFlowServer) Recv() (*SendFlowArg, error) {
	m := new(SendFlowArg)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _GGBFlowSender_SendMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMetaArg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GGBFlowSenderServer).SendMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ggbflow.GGBFlowSender/SendMeta",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GGBFlowSenderServer).SendMeta(ctx, req.(*SendMetaArg))
	}
	return interceptor(ctx, in, info, handler)
}

// GGBFlowSender_ServiceDesc is the grpc.ServiceDesc for GGBFlowSender service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GGBFlowSender_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ggbflow.GGBFlowSender",
	HandlerType: (*GGBFlowSenderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendOneFlow",
			Handler:    _GGBFlowSender_SendOneFlow_Handler,
		},
		{
			MethodName: "SendMeta",
			Handler:    _GGBFlowSender_SendMeta_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendFlow",
			Handler:       _GGBFlowSender_SendFlow_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "gg-bflow.proto",
}

// GGBFlowLoaderClient is the client API for GGBFlowLoader service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GGBFlowLoaderClient interface {
	LoadDiscreteFlow(ctx context.Context, in *LoadDiscreteFlowArg, opts ...grpc.CallOption) (*DiscreteFlowRes, error)
	LoadFlow(ctx context.Context, in *LoadFlowArg, opts ...grpc.CallOption) (GGBFlowLoader_LoadFlowClient, error)
	LoadMeta(ctx context.Context, in *LoadMetaArg, opts ...grpc.CallOption) (*MetaRes, error)
}

type gGBFlowLoaderClient struct {
	cc grpc.ClientConnInterface
}

func NewGGBFlowLoaderClient(cc grpc.ClientConnInterface) GGBFlowLoaderClient {
	return &gGBFlowLoaderClient{cc}
}

func (c *gGBFlowLoaderClient) LoadDiscreteFlow(ctx context.Context, in *LoadDiscreteFlowArg, opts ...grpc.CallOption) (*DiscreteFlowRes, error) {
	out := new(DiscreteFlowRes)
	err := c.cc.Invoke(ctx, "/ggbflow.GGBFlowLoader/LoadDiscreteFlow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gGBFlowLoaderClient) LoadFlow(ctx context.Context, in *LoadFlowArg, opts ...grpc.CallOption) (GGBFlowLoader_LoadFlowClient, error) {
	stream, err := c.cc.NewStream(ctx, &GGBFlowLoader_ServiceDesc.Streams[0], "/ggbflow.GGBFlowLoader/LoadFlow", opts...)
	if err != nil {
		return nil, err
	}
	x := &gGBFlowLoaderLoadFlowClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GGBFlowLoader_LoadFlowClient interface {
	Recv() (*FlowRes, error)
	grpc.ClientStream
}

type gGBFlowLoaderLoadFlowClient struct {
	grpc.ClientStream
}

func (x *gGBFlowLoaderLoadFlowClient) Recv() (*FlowRes, error) {
	m := new(FlowRes)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gGBFlowLoaderClient) LoadMeta(ctx context.Context, in *LoadMetaArg, opts ...grpc.CallOption) (*MetaRes, error) {
	out := new(MetaRes)
	err := c.cc.Invoke(ctx, "/ggbflow.GGBFlowLoader/LoadMeta", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GGBFlowLoaderServer is the server API for GGBFlowLoader service.
// All implementations must embed UnimplementedGGBFlowLoaderServer
// for forward compatibility
type GGBFlowLoaderServer interface {
	LoadDiscreteFlow(context.Context, *LoadDiscreteFlowArg) (*DiscreteFlowRes, error)
	LoadFlow(*LoadFlowArg, GGBFlowLoader_LoadFlowServer) error
	LoadMeta(context.Context, *LoadMetaArg) (*MetaRes, error)
	mustEmbedUnimplementedGGBFlowLoaderServer()
}

// UnimplementedGGBFlowLoaderServer must be embedded to have forward compatible implementations.
type UnimplementedGGBFlowLoaderServer struct {
}

func (UnimplementedGGBFlowLoaderServer) LoadDiscreteFlow(context.Context, *LoadDiscreteFlowArg) (*DiscreteFlowRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadDiscreteFlow not implemented")
}
func (UnimplementedGGBFlowLoaderServer) LoadFlow(*LoadFlowArg, GGBFlowLoader_LoadFlowServer) error {
	return status.Errorf(codes.Unimplemented, "method LoadFlow not implemented")
}
func (UnimplementedGGBFlowLoaderServer) LoadMeta(context.Context, *LoadMetaArg) (*MetaRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadMeta not implemented")
}
func (UnimplementedGGBFlowLoaderServer) mustEmbedUnimplementedGGBFlowLoaderServer() {}

// UnsafeGGBFlowLoaderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GGBFlowLoaderServer will
// result in compilation errors.
type UnsafeGGBFlowLoaderServer interface {
	mustEmbedUnimplementedGGBFlowLoaderServer()
}

func RegisterGGBFlowLoaderServer(s grpc.ServiceRegistrar, srv GGBFlowLoaderServer) {
	s.RegisterService(&GGBFlowLoader_ServiceDesc, srv)
}

func _GGBFlowLoader_LoadDiscreteFlow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadDiscreteFlowArg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GGBFlowLoaderServer).LoadDiscreteFlow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ggbflow.GGBFlowLoader/LoadDiscreteFlow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GGBFlowLoaderServer).LoadDiscreteFlow(ctx, req.(*LoadDiscreteFlowArg))
	}
	return interceptor(ctx, in, info, handler)
}

func _GGBFlowLoader_LoadFlow_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LoadFlowArg)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GGBFlowLoaderServer).LoadFlow(m, &gGBFlowLoaderLoadFlowServer{stream})
}

type GGBFlowLoader_LoadFlowServer interface {
	Send(*FlowRes) error
	grpc.ServerStream
}

type gGBFlowLoaderLoadFlowServer struct {
	grpc.ServerStream
}

func (x *gGBFlowLoaderLoadFlowServer) Send(m *FlowRes) error {
	return x.ServerStream.SendMsg(m)
}

func _GGBFlowLoader_LoadMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadMetaArg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GGBFlowLoaderServer).LoadMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ggbflow.GGBFlowLoader/LoadMeta",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GGBFlowLoaderServer).LoadMeta(ctx, req.(*LoadMetaArg))
	}
	return interceptor(ctx, in, info, handler)
}

// GGBFlowLoader_ServiceDesc is the grpc.ServiceDesc for GGBFlowLoader service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GGBFlowLoader_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ggbflow.GGBFlowLoader",
	HandlerType: (*GGBFlowLoaderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoadDiscreteFlow",
			Handler:    _GGBFlowLoader_LoadDiscreteFlow_Handler,
		},
		{
			MethodName: "LoadMeta",
			Handler:    _GGBFlowLoader_LoadMeta_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "LoadFlow",
			Handler:       _GGBFlowLoader_LoadFlow_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "gg-bflow.proto",
}
