// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: gg-bflow.proto

package gg_bflow

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValueType int32

const (
	ValueType_UNKNOWN ValueType = 0
	ValueType_STR     ValueType = 1
	ValueType_INT     ValueType = 2
	ValueType_FLOAT   ValueType = 3
	ValueType_BOOL    ValueType = 4
)

// Enum value maps for ValueType.
var (
	ValueType_name = map[int32]string{
		0: "UNKNOWN",
		1: "STR",
		2: "INT",
		3: "FLOAT",
		4: "BOOL",
	}
	ValueType_value = map[string]int32{
		"UNKNOWN": 0,
		"STR":     1,
		"INT":     2,
		"FLOAT":   3,
		"BOOL":    4,
	}
)

func (x ValueType) Enum() *ValueType {
	p := new(ValueType)
	*p = x
	return p
}

func (x ValueType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValueType) Descriptor() protoreflect.EnumDescriptor {
	return file_gg_bflow_proto_enumTypes[0].Descriptor()
}

func (ValueType) Type() protoreflect.EnumType {
	return &file_gg_bflow_proto_enumTypes[0]
}

func (x ValueType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValueType.Descriptor instead.
func (ValueType) EnumDescriptor() ([]byte, []int) {
	return file_gg_bflow_proto_rawDescGZIP(), []int{0}
}

type Ok struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string      `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	Meta    []*KeyValue `protobuf:"bytes,2,rep,name=Meta,proto3" json:"Meta,omitempty"`
}

func (x *Ok) Reset() {
	*x = Ok{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gg_bflow_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ok) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ok) ProtoMessage() {}

func (x *Ok) ProtoReflect() protoreflect.Message {
	mi := &file_gg_bflow_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ok.ProtoReflect.Descriptor instead.
func (*Ok) Descriptor() ([]byte, []int) {
	return file_gg_bflow_proto_rawDescGZIP(), []int{0}
}

func (x *Ok) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Ok) GetMeta() []*KeyValue {
	if x != nil {
		return x.Meta
	}
	return nil
}

type HealthCheckRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*KeyValue `protobuf:"bytes,1,rep,name=Data,proto3" json:"Data,omitempty"`
}

func (x *HealthCheckRes) Reset() {
	*x = HealthCheckRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gg_bflow_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HealthCheckRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRes) ProtoMessage() {}

func (x *HealthCheckRes) ProtoReflect() protoreflect.Message {
	mi := &file_gg_bflow_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRes.ProtoReflect.Descriptor instead.
func (*HealthCheckRes) Descriptor() ([]byte, []int) {
	return file_gg_bflow_proto_rawDescGZIP(), []int{1}
}

func (x *HealthCheckRes) GetData() []*KeyValue {
	if x != nil {
		return x.Data
	}
	return nil
}

type LoadArg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
}

func (x *LoadArg) Reset() {
	*x = LoadArg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gg_bflow_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadArg) ProtoMessage() {}

func (x *LoadArg) ProtoReflect() protoreflect.Message {
	mi := &file_gg_bflow_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadArg.ProtoReflect.Descriptor instead.
func (*LoadArg) Descriptor() ([]byte, []int) {
	return file_gg_bflow_proto_rawDescGZIP(), []int{2}
}

func (x *LoadArg) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type SendArg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key     string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	ByteArr []byte `protobuf:"bytes,2,opt,name=ByteArr,proto3" json:"ByteArr,omitempty"`
}

func (x *SendArg) Reset() {
	*x = SendArg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gg_bflow_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendArg) ProtoMessage() {}

func (x *SendArg) ProtoReflect() protoreflect.Message {
	mi := &file_gg_bflow_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendArg.ProtoReflect.Descriptor instead.
func (*SendArg) Descriptor() ([]byte, []int) {
	return file_gg_bflow_proto_rawDescGZIP(), []int{3}
}

func (x *SendArg) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SendArg) GetByteArr() []byte {
	if x != nil {
		return x.ByteArr
	}
	return nil
}

type FlowRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ByteArr []byte `protobuf:"bytes,2,opt,name=ByteArr,proto3" json:"ByteArr,omitempty"`
}

func (x *FlowRes) Reset() {
	*x = FlowRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gg_bflow_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlowRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowRes) ProtoMessage() {}

func (x *FlowRes) ProtoReflect() protoreflect.Message {
	mi := &file_gg_bflow_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowRes.ProtoReflect.Descriptor instead.
func (*FlowRes) Descriptor() ([]byte, []int) {
	return file_gg_bflow_proto_rawDescGZIP(), []int{4}
}

func (x *FlowRes) GetByteArr() []byte {
	if x != nil {
		return x.ByteArr
	}
	return nil
}

type KeyValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key        string    `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Type       ValueType `protobuf:"varint,2,opt,name=Type,proto3,enum=ggbflow.ValueType" json:"Type,omitempty"`
	IntValue   *int64    `protobuf:"varint,3,opt,name=IntValue,proto3,oneof" json:"IntValue,omitempty"`
	StrValue   *string   `protobuf:"bytes,4,opt,name=StrValue,proto3,oneof" json:"StrValue,omitempty"`
	BoolValue  *bool     `protobuf:"varint,5,opt,name=BoolValue,proto3,oneof" json:"BoolValue,omitempty"`
	FloatValue *float32  `protobuf:"fixed32,6,opt,name=FloatValue,proto3,oneof" json:"FloatValue,omitempty"`
}

func (x *KeyValue) Reset() {
	*x = KeyValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gg_bflow_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValue) ProtoMessage() {}

func (x *KeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_gg_bflow_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValue.ProtoReflect.Descriptor instead.
func (*KeyValue) Descriptor() ([]byte, []int) {
	return file_gg_bflow_proto_rawDescGZIP(), []int{5}
}

func (x *KeyValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValue) GetType() ValueType {
	if x != nil {
		return x.Type
	}
	return ValueType_UNKNOWN
}

func (x *KeyValue) GetIntValue() int64 {
	if x != nil && x.IntValue != nil {
		return *x.IntValue
	}
	return 0
}

func (x *KeyValue) GetStrValue() string {
	if x != nil && x.StrValue != nil {
		return *x.StrValue
	}
	return ""
}

func (x *KeyValue) GetBoolValue() bool {
	if x != nil && x.BoolValue != nil {
		return *x.BoolValue
	}
	return false
}

func (x *KeyValue) GetFloatValue() float32 {
	if x != nil && x.FloatValue != nil {
		return *x.FloatValue
	}
	return 0
}

type MetaArg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key  string      `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Meta []*KeyValue `protobuf:"bytes,2,rep,name=Meta,proto3" json:"Meta,omitempty"`
}

func (x *MetaArg) Reset() {
	*x = MetaArg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gg_bflow_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetaArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaArg) ProtoMessage() {}

func (x *MetaArg) ProtoReflect() protoreflect.Message {
	mi := &file_gg_bflow_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaArg.ProtoReflect.Descriptor instead.
func (*MetaArg) Descriptor() ([]byte, []int) {
	return file_gg_bflow_proto_rawDescGZIP(), []int{6}
}

func (x *MetaArg) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *MetaArg) GetMeta() []*KeyValue {
	if x != nil {
		return x.Meta
	}
	return nil
}

type MetaRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key       string      `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Meta      []*KeyValue `protobuf:"bytes,2,rep,name=Meta,proto3" json:"Meta,omitempty"`
	CreatedAt int64       `protobuf:"varint,3,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt int64       `protobuf:"varint,4,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
}

func (x *MetaRes) Reset() {
	*x = MetaRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gg_bflow_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetaRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaRes) ProtoMessage() {}

func (x *MetaRes) ProtoReflect() protoreflect.Message {
	mi := &file_gg_bflow_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaRes.ProtoReflect.Descriptor instead.
func (*MetaRes) Descriptor() ([]byte, []int) {
	return file_gg_bflow_proto_rawDescGZIP(), []int{7}
}

func (x *MetaRes) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *MetaRes) GetMeta() []*KeyValue {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *MetaRes) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *MetaRes) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

var File_gg_bflow_proto protoreflect.FileDescriptor

var file_gg_bflow_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x67, 0x67, 0x2d, 0x62, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x07, 0x67, 0x67, 0x62, 0x66, 0x6c, 0x6f, 0x77, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x45, 0x0a, 0x02, 0x4f, 0x6b, 0x12, 0x18, 0x0a, 0x07,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x25, 0x0a, 0x04, 0x4d, 0x65, 0x74, 0x61, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x67, 0x67, 0x62, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x4b,
	0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x04, 0x4d, 0x65, 0x74, 0x61, 0x22, 0x37, 0x0a,
	0x0e, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x12,
	0x25, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x67, 0x67, 0x62, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x1b, 0x0a, 0x07, 0x4c, 0x6f, 0x61, 0x64, 0x41, 0x72,
	0x67, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x4b, 0x65, 0x79, 0x22, 0x35, 0x0a, 0x07, 0x53, 0x65, 0x6e, 0x64, 0x41, 0x72, 0x67, 0x12, 0x10,
	0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79,
	0x12, 0x18, 0x0a, 0x07, 0x42, 0x79, 0x74, 0x65, 0x41, 0x72, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x07, 0x42, 0x79, 0x74, 0x65, 0x41, 0x72, 0x72, 0x22, 0x23, 0x0a, 0x07, 0x46, 0x6c,
	0x6f, 0x77, 0x52, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x42, 0x79, 0x74, 0x65, 0x41, 0x72, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x42, 0x79, 0x74, 0x65, 0x41, 0x72, 0x72, 0x22,
	0x85, 0x02, 0x0a, 0x08, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x26,
	0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x67,
	0x67, 0x62, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a, 0x08, 0x49, 0x6e, 0x74, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x08, 0x49, 0x6e, 0x74, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x88, 0x01, 0x01, 0x12, 0x1f, 0x0a, 0x08, 0x53, 0x74, 0x72, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x08, 0x53, 0x74, 0x72,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x88, 0x01, 0x01, 0x12, 0x21, 0x0a, 0x09, 0x42, 0x6f, 0x6f, 0x6c,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x48, 0x02, 0x52, 0x09, 0x42,
	0x6f, 0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x88, 0x01, 0x01, 0x12, 0x23, 0x0a, 0x0a, 0x46,
	0x6c, 0x6f, 0x61, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x48,
	0x03, 0x52, 0x0a, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x88, 0x01, 0x01,
	0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x49, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x0b, 0x0a,
	0x09, 0x5f, 0x53, 0x74, 0x72, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x42,
	0x6f, 0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x46, 0x6c, 0x6f,
	0x61, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x42, 0x0a, 0x07, 0x4d, 0x65, 0x74, 0x61, 0x41,
	0x72, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x4b, 0x65, 0x79, 0x12, 0x25, 0x0a, 0x04, 0x4d, 0x65, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x67, 0x67, 0x62, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x4b, 0x65, 0x79,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x04, 0x4d, 0x65, 0x74, 0x61, 0x22, 0x7e, 0x0a, 0x07, 0x4d,
	0x65, 0x74, 0x61, 0x52, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x25, 0x0a, 0x04, 0x4d, 0x65, 0x74, 0x61,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x67, 0x67, 0x62, 0x66, 0x6c, 0x6f, 0x77,
	0x2e, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x04, 0x4d, 0x65, 0x74, 0x61, 0x12,
	0x1c, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1c, 0x0a,
	0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x2a, 0x3f, 0x0a, 0x09, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e,
	0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x53, 0x54, 0x52, 0x10, 0x01, 0x12, 0x07,
	0x0a, 0x03, 0x49, 0x4e, 0x54, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x46, 0x4c, 0x4f, 0x41, 0x54,
	0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x42, 0x4f, 0x4f, 0x4c, 0x10, 0x04, 0x32, 0xf0, 0x02, 0x0a,
	0x07, 0x47, 0x47, 0x42, 0x46, 0x6c, 0x6f, 0x77, 0x12, 0x3e, 0x0a, 0x0b, 0x48, 0x65, 0x61, 0x6c,
	0x74, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a,
	0x17, 0x2e, 0x67, 0x67, 0x62, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x12, 0x36, 0x0a, 0x10, 0x4c, 0x6f, 0x61, 0x64,
	0x44, 0x69, 0x73, 0x63, 0x72, 0x65, 0x74, 0x65, 0x46, 0x6c, 0x6f, 0x77, 0x12, 0x10, 0x2e, 0x67,
	0x67, 0x62, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x4c, 0x6f, 0x61, 0x64, 0x41, 0x72, 0x67, 0x1a, 0x10,
	0x2e, 0x67, 0x67, 0x62, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x46, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x73,
	0x12, 0x31, 0x0a, 0x10, 0x53, 0x65, 0x6e, 0x64, 0x44, 0x69, 0x73, 0x63, 0x72, 0x65, 0x74, 0x65,
	0x46, 0x6c, 0x6f, 0x77, 0x12, 0x10, 0x2e, 0x67, 0x67, 0x62, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x53,
	0x65, 0x6e, 0x64, 0x41, 0x72, 0x67, 0x1a, 0x0b, 0x2e, 0x67, 0x67, 0x62, 0x66, 0x6c, 0x6f, 0x77,
	0x2e, 0x4f, 0x6b, 0x12, 0x32, 0x0a, 0x08, 0x4c, 0x6f, 0x61, 0x64, 0x46, 0x6c, 0x6f, 0x77, 0x12,
	0x10, 0x2e, 0x67, 0x67, 0x62, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x4c, 0x6f, 0x61, 0x64, 0x41, 0x72,
	0x67, 0x1a, 0x10, 0x2e, 0x67, 0x67, 0x62, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x46, 0x6c, 0x6f, 0x77,
	0x52, 0x65, 0x73, 0x28, 0x01, 0x30, 0x01, 0x12, 0x2b, 0x0a, 0x08, 0x53, 0x65, 0x6e, 0x64, 0x46,
	0x6c, 0x6f, 0x77, 0x12, 0x10, 0x2e, 0x67, 0x67, 0x62, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x53, 0x65,
	0x6e, 0x64, 0x41, 0x72, 0x67, 0x1a, 0x0b, 0x2e, 0x67, 0x67, 0x62, 0x66, 0x6c, 0x6f, 0x77, 0x2e,
	0x4f, 0x6b, 0x28, 0x01, 0x12, 0x29, 0x0a, 0x08, 0x53, 0x61, 0x76, 0x65, 0x4d, 0x65, 0x74, 0x61,
	0x12, 0x10, 0x2e, 0x67, 0x67, 0x62, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x41,
	0x72, 0x67, 0x1a, 0x0b, 0x2e, 0x67, 0x67, 0x62, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x4f, 0x6b, 0x12,
	0x2e, 0x0a, 0x08, 0x4c, 0x6f, 0x61, 0x64, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x10, 0x2e, 0x67, 0x67,
	0x62, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x4c, 0x6f, 0x61, 0x64, 0x41, 0x72, 0x67, 0x1a, 0x10, 0x2e,
	0x67, 0x67, 0x62, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x73, 0x42,
	0x17, 0x5a, 0x15, 0x61, 0x70, 0x70, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x3b,
	0x67, 0x67, 0x5f, 0x62, 0x66, 0x6c, 0x6f, 0x77, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gg_bflow_proto_rawDescOnce sync.Once
	file_gg_bflow_proto_rawDescData = file_gg_bflow_proto_rawDesc
)

func file_gg_bflow_proto_rawDescGZIP() []byte {
	file_gg_bflow_proto_rawDescOnce.Do(func() {
		file_gg_bflow_proto_rawDescData = protoimpl.X.CompressGZIP(file_gg_bflow_proto_rawDescData)
	})
	return file_gg_bflow_proto_rawDescData
}

var file_gg_bflow_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gg_bflow_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_gg_bflow_proto_goTypes = []interface{}{
	(ValueType)(0),         // 0: ggbflow.ValueType
	(*Ok)(nil),             // 1: ggbflow.Ok
	(*HealthCheckRes)(nil), // 2: ggbflow.HealthCheckRes
	(*LoadArg)(nil),        // 3: ggbflow.LoadArg
	(*SendArg)(nil),        // 4: ggbflow.SendArg
	(*FlowRes)(nil),        // 5: ggbflow.FlowRes
	(*KeyValue)(nil),       // 6: ggbflow.KeyValue
	(*MetaArg)(nil),        // 7: ggbflow.MetaArg
	(*MetaRes)(nil),        // 8: ggbflow.MetaRes
	(*emptypb.Empty)(nil),  // 9: google.protobuf.Empty
}
var file_gg_bflow_proto_depIdxs = []int32{
	6,  // 0: ggbflow.Ok.Meta:type_name -> ggbflow.KeyValue
	6,  // 1: ggbflow.HealthCheckRes.Data:type_name -> ggbflow.KeyValue
	0,  // 2: ggbflow.KeyValue.Type:type_name -> ggbflow.ValueType
	6,  // 3: ggbflow.MetaArg.Meta:type_name -> ggbflow.KeyValue
	6,  // 4: ggbflow.MetaRes.Meta:type_name -> ggbflow.KeyValue
	9,  // 5: ggbflow.GGBFlow.HealthCheck:input_type -> google.protobuf.Empty
	3,  // 6: ggbflow.GGBFlow.LoadDiscreteFlow:input_type -> ggbflow.LoadArg
	4,  // 7: ggbflow.GGBFlow.SendDiscreteFlow:input_type -> ggbflow.SendArg
	3,  // 8: ggbflow.GGBFlow.LoadFlow:input_type -> ggbflow.LoadArg
	4,  // 9: ggbflow.GGBFlow.SendFlow:input_type -> ggbflow.SendArg
	7,  // 10: ggbflow.GGBFlow.SaveMeta:input_type -> ggbflow.MetaArg
	3,  // 11: ggbflow.GGBFlow.LoadMeta:input_type -> ggbflow.LoadArg
	2,  // 12: ggbflow.GGBFlow.HealthCheck:output_type -> ggbflow.HealthCheckRes
	5,  // 13: ggbflow.GGBFlow.LoadDiscreteFlow:output_type -> ggbflow.FlowRes
	1,  // 14: ggbflow.GGBFlow.SendDiscreteFlow:output_type -> ggbflow.Ok
	5,  // 15: ggbflow.GGBFlow.LoadFlow:output_type -> ggbflow.FlowRes
	1,  // 16: ggbflow.GGBFlow.SendFlow:output_type -> ggbflow.Ok
	1,  // 17: ggbflow.GGBFlow.SaveMeta:output_type -> ggbflow.Ok
	8,  // 18: ggbflow.GGBFlow.LoadMeta:output_type -> ggbflow.MetaRes
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_gg_bflow_proto_init() }
func file_gg_bflow_proto_init() {
	if File_gg_bflow_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gg_bflow_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ok); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gg_bflow_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HealthCheckRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gg_bflow_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadArg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gg_bflow_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendArg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gg_bflow_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FlowRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gg_bflow_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gg_bflow_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetaArg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gg_bflow_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetaRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_gg_bflow_proto_msgTypes[5].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gg_bflow_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gg_bflow_proto_goTypes,
		DependencyIndexes: file_gg_bflow_proto_depIdxs,
		EnumInfos:         file_gg_bflow_proto_enumTypes,
		MessageInfos:      file_gg_bflow_proto_msgTypes,
	}.Build()
	File_gg_bflow_proto = out.File
	file_gg_bflow_proto_rawDesc = nil
	file_gg_bflow_proto_goTypes = nil
	file_gg_bflow_proto_depIdxs = nil
}
